### ISSUE TITLE
Compilation Error In Visual Studio Code

### ISSUE THREAD

**Issue by nextecsolutions** [mohamed-sallam/Al-Miqata#1]
Asalam-U-Aliakum Brother,
                                        I want to build this project for my mosque but i couldn't compile the project in Visual Studio Code Please help if i am missing something while compiling the code in Platform IO, If possible can you come up with detailed instructions on how to compile the project in Visual studio Code, Your response would be much appreciated.

Regards,
Bilal

**Comment by mohamed-sallam** [comment]
@nextecsolutions 
وعليكم السلام ورحمة الله وبركاته
I wrote a detailed description of how to build and run it, check it out in `README.md`, don't forget to pull, there are new commits.
If you want to discuss any matter related to Al-Miqata, you can join [this Discord server](https://discord.gg/bKBzGt6g).
Salaam
